---
title: "Quiz Version 1"
author: "Immanuel Williams PhD"
date: "`r Sys.Date()`"
output: learnr::tutorial
runtime: shiny_prerendered
---




```{r setup, include=FALSE}
library(tidyverse)
library(learnr)
library(gradethis)
library(gato365dsh2024)
gradethis::gradethis_setup()
knitr::opts_chunk$set(echo = FALSE)

```



```{r loaddata}
micoeconomics_concepts_df <- readxl::read_xlsx(here::here("Data","micoeconomics_concepts.xlsx"))
```

```{r}
selected_unit = 1 ## Specified by User
focused_concepts_df <- micoeconomics_concepts_df %>%
  filter(`Unit Name` == selected_unit)
```


```{r}
correct_options <- 1
wrong_options_diff_unit <- 3
wrong_options_same_unit <- 2
number_of_options <-  correct_options + wrong_options_diff_unit + wrong_options_same_unit


selected_row_df <- focused_concepts_df %>%
  sample_n(correct_options)
```



```{r}
# 1) Filter the selected row from microeconomics_concepts_df and select 3 rows randomly
diff_unit_options_df <-  micoeconomics_concepts_df %>%
  anti_join(selected_row_df, by = c("Concept","Unit Name")) %>%
  sample_n(wrong_options_diff_unit)

# 2) Filter the selected row from focused_concepts_df and select 2 options
same_unit_options_df <- focused_concepts_df %>%
  anti_join(selected_row_df, by = c("Concept","Unit Name")) %>%
  sample_n(wrong_options_same_unit)

wrong_options_df <- bind_rows(diff_unit_options_df,same_unit_options_df) %>% 
  mutate(correct = FALSE)

all_options_df <- selected_row_df %>% 
  mutate(correct = TRUE) %>% 
  bind_rows(wrong_options_df) %>% 
  sample_n(number_of_options)
```


```{r quiz}
quiz(
  question(text = paste0("1. What is ",selected_row_df$Concept,"?"),
           answer(all_options_df$`Abbreviated Definition`[1], correct = all_options_df$correct[1]),
           answer(all_options_df$`Abbreviated Definition`[2], correct = all_options_df$correct[2]),
           answer(all_options_df$`Abbreviated Definition`[3], correct = all_options_df$correct[3]),
           answer(all_options_df$`Abbreviated Definition`[4], correct = all_options_df$correct[4]),
           answer(all_options_df$`Abbreviated Definition`[5], correct = all_options_df$correct[5]),
           answer(all_options_df$`Abbreviated Definition`[6], correct = all_options_df$correct[6])

  )

)

```


